// products.js

const PRODUCTS = [
   { id: 'p1', name: 'Royal Dinner Set (72 pc)', price: 12199,
     desc: 'Ceramic, dishwasher-safe, premium gloss finish.',
     img: 'itemno1.jpeg'},
   { id: 'p2', name: 'Stainless Steel Cutlery Set (16 pc)', price: 1299,
     desc: 'Mirror-polished, rust-free, modern handle design.',
     img: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=80' },
   { id: 'p3', name: 'Dinner set(72 pcs)', price: 12299,
     desc: 'Lead-free crystal, perfect for juice, water, or drinks.',
     img: 'itemno2.jpeg' },
   { id: 'p5', name: 'Tray set(3 pcs)', price: 2999,
     desc: 'Heavy-base cut-glass cigarette ashtray, elegant for table or lounge.',
     img: 'itemno3.jpeg' },
   { id: 'p6', name: 'Water bottle', price: 199,
     desc: 'BPA-free, leak-proof, insulated — keeps drinks cool for hours.',
     img: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=800&q=80' },
   { id: 'p7', name: 'Jugs and Glasses', price: 599,
     desc: 'Food-grade steel insert, airtight seal, spill-resistant.',
     img: 'itemno4.jpeg' },
   { id: 'p8', name: 'Tray set', price: 1199,
     desc: 'Food-grade steel insert, airtight seal, spill-resistant.',
     img: 'pic1.jpeg' },
   { id: 'p9', name: 'Cutlery set', price: 2499,
     desc: 'golden color spoons and fork.',
     img: 'pic2.jpeg' },
   { id: 'p10', name: 'Dinner set with flower design(72 pcs)', price: 7999,
     desc: 'flower design plates.',
     img: 'pic3.jpeg' },
   { id: 'p11', name: 'Dinner set with flower design(72 pcs)', price: 14999,
     desc: 'double glazed dinner set with unique material.',
     img: 'pic4.jpeg' },
   { id: 'p12', name: 'Golden serving tray', price: 1149,
     desc: 'golden color gleam serving tray',
     img: 'pic5.jpeg' },
   { id: 'p13', name: 'Safari water bottles', price:299  ,
     desc: 'safari flipper bottle',
     img: 'pic6.jpeg' },
   { id: 'p14', name: 'Salt and Pepper set 2 piece', price: 399,
     desc: 'salt and pepper set',
     img: 'pic7.jpeg' },
   { id: 'p15', name: 'Royal dinner set(72 pcs)', price: 9999,
     desc: 'dinner set',
     img: 'pic8.jpeg' },
   { id: 'p16', name: 'Iconic dinner set(76 pcs)', price: 8999,
     desc: 'dinner set',
     img: 'pic10.jpeg' },
   { id: 'p17', name: 'Royal mellamine dinner set(72 pcs)', price: 11499,
     desc: 'dinner set',
     img: 'pic11.jpeg' },
   { id: 'p18', name: 'Premium glasses set(6 pcs)', price: 499,
     desc: 'dinner set',
     img: 'pic12.jpeg' },
   { id: 'p19', name: '04 size spoons', price: 1499,
     desc: 'dinner set',
     img: 'pic13.jpeg' },
   { id: 'p22', name: 'Flower design dinner set(76 pcs)', price: 11999,
     desc: 'High malleable dinner set',
     img: 'pic16.jpeg' },
   { id: 'p23', name: 'Sipper', price: 1599,
     desc: 'Stanley with  red and white color in metal quality',
     img: 'sipper.jpeg' },
   { id: 'p26', name: 'Jugs', price: 1499,
     desc: 'Black berries jug with flower design(1 pcs)',
     img: 'jugs.jpeg' },
   { id: 'p27', name: 'Glass', price:649 ,
     desc: ' High-quality water drnking glasses(1pcs)',
     img: 'styleglass.jpeg' },
   { id: 'p28', name: 'Dinner set(72 pcs)', price: 12499,
     desc: ' High-quality water drnking glasses',
     img: 'dinner1set.jpeg' },
   { id: 'p29', name: 'High quality  vaccum flask jug set with simple blue flower design (1pcs)', price: 799,
     desc: 'Thermos for Teas and Water (1pcs)',
     img: 'vaccumflaskjug.jpeg' },
   { id: 'p30', name: 'Vaccum Bottles', price: 999,
     desc: 'Vaccum water bottles for school (1pcs)',
     img: 'vaccumbottle.jpeg' },
   { id: 'p31', name: 'Salt and Pepper set ', price: 799,
     desc: 'salt and pepper set with brown and white color (6pcs set)',
     img: 'saltandpeper.jpeg' },
   { id: 'p32', name: 'Glass set ', price: 2299,
     desc: 'Delisoga glass ware in white color (6pcs set)',
     img: 'Thermos.jpeg' },
   { id: 'p33', name: 'Tray set ', price: 2999,
     desc: 'Tray set with wooden material in flower design(3pcs set)',
     img: 'trayset.jpeg' },
   { id: 'p34', name: 'Plastic jug ', price: 4999,
     desc: 'Golden color jug with 2tr capacity(jug and 6 glass)',
     img: 'plasticjug.jpeg' },
   { id: 'p35', name: 'Ice cream set ', price: 1199,
     desc: 'White color color ice cream bowl set(6 pcs)',
     img: 'icecreamset.jpeg' },
   { id: 'p36', name: 'Plastic box ', price: 399,
     desc: 'Blue color plastic box(1 pcs)',
     img: 'plasticbox.jpeg' },
   { id: 'p36', name: 'Juice glender ', price: 1999,
     desc: 'juice glender with metal quality',
     img: '55.jpeg' },
   { id: 'p37', name: 'Plastic box ', price: 499,
     desc: 'party jug with plastic material in blue color',
     img: '88.jpeg' },
   { id: 'p38', name: 'Mug', price: 499,
     desc: ' Mug for drinking water in pink color cup with glass plate and glass material',
     img: 'cup.jpeg' },
   { id: 'p39', name: 'Sipper', price: 1299,
     desc: 'pink color sipper for girls',
     img: 'sipper4.jpeg' },
   { id: 'p40', name: 'Vegetable cutter', price:599 ,
     desc: 'vegetable cutter with good quality blade',
     img: 'cutter4.jpeg' }
 ];

 window.PRODUCTS = PRODUCTS; // Keeps it accessible globally across your files
